project:
  type: website

website:
  title: Decoding Inequality 2025
  favicon: android-chrome-512x512.png
  open-graph: true
  twitter-card: true
  site-url: https://dhbern.github.io/decoding-inequality-2025/
  repo-url: https://github.com/DHBern/decoding-inequality-2025/
  issue-url: https://github.com/DHBern/decoding-inequality-2025/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    logo: android-chrome-512x512.png
    logo-alt: ''
    logo-href: ''
    title: Decoding Inequality 2025
    tools:
      - icon: github
        url: https://github.com/DHBern/decoding-inequality-2025/
    left:
      - href: contents/home.qmd
        text: Kursbeschreibung
      - href: contents/syllabus.qmd
      - href: contents/interesting-stuff.qmd
      - href: contents/blog.qmd
      - href: contents/about.qmd

  sidebar:
    collapse-level: 1
    contents:
      - href: contents/home.qmd
        text: Kursbeschreibung
      - href: contents/syllabus.qmd
      - href: contents/interesting-stuff.qmd
      - section: Blog
        href: contents/blog.qmd
        contents: contents/posts/*
      - href: contents/about.qmd

format:
  html:
    link-external-newwindow: true
    toc: true
    citations-hover: true
    crossrefs-hover: true
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    css: styles.css
    page-layout: full

freeze: true

editor: visual
